<?php

namespace Database\Seeders;

use App\Models\Country;
use Illuminate\Database\Seeder;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            ['id' => '1', 'name' => 'Argentina', 'prefix' => 'AR', 'number' => '+54'],
            ['id' => '2', 'name' => 'Bolivia', 'prefix' => 'BO', 'number' => '+591'],
            ['id' => '3', 'name' => 'Chile', 'prefix' => 'CL', 'number' => '+56'],
            ['id' => '4', 'name' => 'Colombia', 'prefix' => 'CO', 'number' => '+57'],
            ['id' => '5', 'name' => 'Costa Rica', 'prefix' => 'CR', 'number' => '+506'],
            ['id' => '6', 'name' => 'Cuba', 'prefix' => 'CU', 'number' => '+53'],
            ['id' => '7', 'name' => 'Ecuador', 'prefix' => 'EC', 'number' => '+593'],
            ['id' => '8', 'name' => 'El Salvador', 'prefix' => 'SV', 'number' => '+503'],
            ['id' => '9', 'name' => 'España', 'prefix' => 'ES', 'number' => '+34'],
            ['id' => '10', 'name' => 'Guatemala', 'prefix' => 'GT', 'number' => '+502'],
            ['id' => '11', 'name' => 'Honduras', 'prefix' => 'HN', 'number' => '+504'],
            ['id' => '12', 'name' => 'México', 'prefix' => 'MX', 'number' => '+52'],
            ['id' => '13', 'name' => 'Nicaragua', 'prefix' => 'NI', 'number' => '+505'],
            ['id' => '14', 'name' => 'Panamá', 'prefix' => 'PA', 'number' => '+507'],
            ['id' => '15', 'name' => 'Paraguay', 'prefix' => 'PY', 'number' => '+595'],
            ['id' => '16', 'name' => 'Perú', 'prefix' => 'PE', 'number' => '+51'],
            ['id' => '17', 'name' => 'Puerto Rico', 'prefix' => 'PR', 'number' => '+1'],
            ['id' => '18', 'name' => 'República Dominicana', 'prefix' => 'DO', 'number' => '+1'],
            ['id' => '19', 'name' => 'Uruguay', 'prefix' => 'UY', 'number' => '+598'],
            ['id' => '20', 'name' => 'Venezuela', 'prefix' => 'VE', 'number' => '+58'],
            ['id' => '21', 'name' => 'Afganistán', 'prefix' => 'AF', 'number' => '+93'],
            ['id' => '22', 'name' => 'Albania', 'prefix' => 'AL', 'number' => '+355'],
            ['id' => '23', 'name' => 'Alemania', 'prefix' => 'DE', 'number' => '+49'],
            ['id' => '24', 'name' => 'Andorra', 'prefix' => 'AD', 'number' => '+376'],
            ['id' => '25', 'name' => 'Angola', 'prefix' => 'AO', 'number' => '+244'],
            ['id' => '26', 'name' => 'Anguila', 'prefix' => 'AI', 'number' => '+1 264'],
            ['id' => '27', 'name' => 'Antártida', 'prefix' => 'AQ', 'number' => '+672'],
            ['id' => '28', 'name' => 'Antigua y Barbuda', 'prefix' => 'AG', 'number' => '+1 268'],
            ['id' => '29', 'name' => 'Arabia Saudita', 'prefix' => 'SA', 'number' => '+966'],
            ['id' => '30', 'name' => 'Argelia', 'prefix' => 'DZ', 'number' => '+213'],
            ['id' => '31', 'name' => 'Armenia', 'prefix' => 'AM', 'number' => '+374'],
            ['id' => '32', 'name' => 'Aruba', 'prefix' => 'AW', 'number' => '+297'],
            ['id' => '33', 'name' => 'Australia', 'prefix' => 'AU', 'number' => '+61'],
            ['id' => '34', 'name' => 'Austria', 'prefix' => 'AT', 'number' => '+43'],
            ['id' => '35', 'name' => 'Azerbaiyán', 'prefix' => 'AZ', 'number' => '+994'],
            ['id' => '36', 'name' => 'Bahamas', 'prefix' => 'BS', 'number' => '+1'],
            ['id' => '37', 'name' => 'Bangladesh', 'prefix' => 'BD', 'number' => '+880'],
            ['id' => '38', 'name' => 'Barbados', 'prefix' => 'BB', 'number' => '+1'],
            ['id' => '39', 'name' => 'Bahréin', 'prefix' => 'BH', 'number' => '+973'],
            ['id' => '40', 'name' => 'Bélgica', 'prefix' => 'BE', 'number' => '+32'],
            ['id' => '41', 'name' => 'Belice', 'prefix' => 'BZ', 'number' => '+501'],
            ['id' => '42', 'name' => 'Benín', 'prefix' => 'BJ', 'number' => '+229'],
            ['id' => '43', 'name' => 'Bermudas', 'prefix' => 'BM', 'number' => '+1'],
            ['id' => '44', 'name' => 'Bielorrusia', 'prefix' => 'BY', 'number' => '+375'],
            ['id' => '45', 'name' => 'Bonaire, San Eustaquio y Saba', 'prefix' => 'BQ', 'number' => '+5993'],
            ['id' => '46', 'name' => 'Bosnia y Herzegovina', 'prefix' => 'BA', 'number' => '+387'],
            ['id' => '47', 'name' => 'Botsuana', 'prefix' => 'BW', 'number' => '+267'],
            ['id' => '48', 'name' => 'Brasil', 'prefix' => 'BR', 'number' => '+55'],
            ['id' => '49', 'name' => 'Brunéi Darussalam', 'prefix' => 'BN', 'number' => '+673'],
            ['id' => '50', 'name' => 'Bulgaria', 'prefix' => 'BG', 'number' => '+359'],
            ['id' => '51', 'name' => 'Burkina Faso', 'prefix' => 'BF', 'number' => '+226'],
            ['id' => '52', 'name' => 'Burundi', 'prefix' => 'BI', 'number' => '+257'],
            ['id' => '53', 'name' => 'Bután', 'prefix' => 'BT', 'number' => '+975'],
            ['id' => '54', 'name' => 'Cabo Verde', 'prefix' => 'CV', 'number' => '+238'],
            ['id' => '55', 'name' => 'Camboya', 'prefix' => 'KH', 'number' => '+855'],
            ['id' => '56', 'name' => 'Camerún', 'prefix' => 'CM', 'number' => '+237'],
            ['id' => '57', 'name' => 'Canadá', 'prefix' => 'CA', 'number' => '+1'],
            ['id' => '58', 'name' => 'Chad', 'prefix' => 'TD', 'number' => '+235'],
            ['id' => '59', 'name' => 'China', 'prefix' => 'CN', 'number' => '+86'],
            ['id' => '60', 'name' => 'Chipre', 'prefix' => 'CY', 'number' => '+357'],
            ['id' => '61', 'name' => 'Comoras', 'prefix' => 'KM', 'number' => '+269'],
            ['id' => '62', 'name' => 'Congo', 'prefix' => 'CG', 'number' => '+242'],
            ['id' => '63', 'name' => 'Congo (República Democrática)', 'prefix' => 'CD', 'number' => '+243'],
            ['id' => '64', 'name' => 'Corea', 'prefix' => 'KP', 'number' => '+850'],
            ['id' => '65', 'name' => 'Corea (República Democrática Popular)', 'prefix' => 'KR', 'number' => '+82'],
            ['id' => '66', 'name' => 'Costa de Marfil', 'prefix' => 'CI', 'number' => '+225'],
            ['id' => '67', 'name' => 'Croacia', 'prefix' => 'HR', 'number' => '+385'],
            ['id' => '68', 'name' => 'Curazao', 'prefix' => 'CW', 'number' => '+599'],
            ['id' => '69', 'name' => 'Dinamarca', 'prefix' => 'DK', 'number' => '+45'],
            ['id' => '70', 'name' => 'Dominica', 'prefix' => 'DM', 'number' => '+1'],
            ['id' => '71', 'name' => 'Egipto', 'prefix' => 'EG', 'number' => '+20'],
            ['id' => '72', 'name' => 'Emiratos Árabes Unidos', 'prefix' => 'AE', 'number' => '+971'],
            ['id' => '73', 'name' => 'Eritrea', 'prefix' => 'ER', 'number' => '+291'],
            ['id' => '74', 'name' => 'Eslovaquia', 'prefix' => 'SK', 'number' => '+421'],
            ['id' => '75', 'name' => 'Eslovenia', 'prefix' => 'SI', 'number' => '+386'],
            ['id' => '76', 'name' => 'Estados Unidos', 'prefix' => 'US', 'number' => '+1'],
            ['id' => '77', 'name' => 'Estonia', 'prefix' => 'EE', 'number' => '+372'],
            ['id' => '78', 'name' => 'Etiopía', 'prefix' => 'ET', 'number' => '+251'],
            ['id' => '79', 'name' => 'Filipinas', 'prefix' => 'PH', 'number' => '+63'],
            ['id' => '80', 'name' => 'Finlandia', 'prefix' => 'FI', 'number' => '+358'],
            ['id' => '81', 'name' => 'Fiyi', 'prefix' => 'FJ', 'number' => '+679'],
            ['id' => '82', 'name' => 'Francia', 'prefix' => 'FR', 'number' => '+33'],
            ['id' => '83', 'name' => 'Gabón', 'prefix' => 'GA', 'number' => '+241'],
            ['id' => '84', 'name' => 'Gambia', 'prefix' => 'GM', 'number' => '+220'],
            ['id' => '85', 'name' => 'Georgia', 'prefix' => 'GE', 'number' => '+995'],
            ['id' => '86', 'name' => 'Georgia del Sur y Las Islas Sandwich del Sur', 'prefix' => 'GS', 'number' => '+500'],
            ['id' => '87', 'name' => 'Ghana', 'prefix' => 'GH', 'number' => '+233'],
            ['id' => '88', 'name' => 'Gibraltar', 'prefix' => 'GI', 'number' => '+350'],
            ['id' => '89', 'name' => 'Granada', 'prefix' => 'GD', 'number' => '+1473'],
            ['id' => '90', 'name' => 'Grecia', 'prefix' => 'GR', 'number' => '+30'],
            ['id' => '91', 'name' => 'Groenlandia', 'prefix' => 'GL', 'number' => '+299'],
            ['id' => '92', 'name' => 'Guadalupe', 'prefix' => 'GP', 'number' => '+590'],
            ['id' => '93', 'name' => 'Guam', 'prefix' => 'GU', 'number' => '+1671'],
            ['id' => '94', 'name' => 'Guayana Francesa', 'prefix' => 'GF', 'number' => '+594'],
            ['id' => '95', 'name' => 'Guernsey', 'prefix' => 'GG', 'number' => '+441481'],
            ['id' => '96', 'name' => 'Guinea', 'prefix' => 'GN', 'number' => '+224'],
            ['id' => '97', 'name' => 'Guinea Ecuatorial', 'prefix' => 'GQ', 'number' => '+240'],
            ['id' => '98', 'name' => 'Guinea-Bisaáu', 'prefix' => 'GW', 'number' => '+245'],
            ['id' => '99', 'name' => 'Guyana', 'prefix' => 'GY', 'number' => '+592'],
            ['id' => '100', 'name' => 'Haití', 'prefix' => 'HT', 'number' => '+509'],
            ['id' => '101', 'name' => 'Hong Kong', 'prefix' => 'HK', 'number' => '+852'],
            ['id' => '102', 'name' => 'Hungría', 'prefix' => 'HU', 'number' => '+36'],
            ['id' => '103', 'name' => 'India', 'prefix' => 'IN', 'number' => '+91'],
            ['id' => '104', 'name' => 'Indonesia', 'prefix' => 'ID', 'number' => '+62'],
            ['id' => '105', 'name' => 'Irak', 'prefix' => 'IQ', 'number' => '+964'],
            ['id' => '106', 'name' => 'Irán', 'prefix' => 'IR', 'number' => '+98'],
            ['id' => '107', 'name' => 'Irlanda', 'prefix' => 'IE', 'number' => '+353'],
            ['id' => '108', 'name' => 'Isla Bouvet', 'prefix' => 'BV', 'number' => '+47'],
            ['id' => '109', 'name' => 'Isla de Man', 'prefix' => 'IM', 'number' => '+44'],
            ['id' => '110', 'name' => 'Isla de Navidad', 'prefix' => 'CX', 'number' => '+61'],
            ['id' => '111', 'name' => 'Isla Heard e Islas Mcdonald', 'prefix' => 'HM', 'number' => '+61'],
            ['id' => '112', 'name' => 'Isla Norfolk', 'prefix' => 'NF', 'number' => '+672'],
            ['id' => '113', 'name' => 'Islandia', 'prefix' => 'IS', 'number' => '+354'],
            ['id' => '114', 'name' => 'Islas Åland', 'prefix' => 'AX', 'number' => '+35818'],
            ['id' => '115', 'name' => 'Islas Caimán', 'prefix' => 'KY', 'number' => '+1354'],
            ['id' => '116', 'name' => 'Islas Cocos Keeling)', 'prefix' => 'CC', 'number' => '+61'],
            ['id' => '117', 'name' => 'Islas Cook', 'prefix' => 'CK', 'number' => '+682'],
            ['id' => '118', 'name' => 'Islas Feroe', 'prefix' => 'FO', 'number' => '+298'],
            ['id' => '119', 'name' => 'Islas Marianas del Norte', 'prefix' => 'MP', 'number' => '+1670'],
            ['id' => '120', 'name' => 'Islas Marshall', 'prefix' => 'MH', 'number' => '+692'],
            ['id' => '121', 'name' => 'Islas Salomón', 'prefix' => 'SB', 'number' => '+677'],
            ['id' => '122', 'name' => 'Islas Turcos y Caicos', 'prefix' => 'TC', 'number' => '+1649'],
            ['id' => '123', 'name' => 'Islas Ultramarinas Menores de Estados Unidos', 'prefix' => 'UM', 'number' => '+246'],
            ['id' => '124', 'name' => 'Islas Vírgenes Británicas', 'prefix' => 'VG', 'number' => '+1284'],
            ['id' => '125', 'name' => 'Islas Vírgenes Ee.Uu.', 'prefix' => 'VI', 'number' => '+1340'],
            ['id' => '126', 'name' => 'Israel', 'prefix' => 'IL', 'number' => '+972'],
            ['id' => '127', 'name' => 'Italia', 'prefix' => 'IT', 'number' => '+39'],
            ['id' => '128', 'name' => 'Jamaica', 'prefix' => 'JM', 'number' => '+1876'],
            ['id' => '129', 'name' => 'Japón', 'prefix' => 'JP', 'number' => '+81'],
            ['id' => '130', 'name' => 'Jersey', 'prefix' => 'JE', 'number' => '+44'],
            ['id' => '131', 'name' => 'Jordania', 'prefix' => 'JO', 'number' => '+962'],
            ['id' => '132', 'name' => 'Kazajistán', 'prefix' => 'KZ', 'number' => '+7'],
            ['id' => '133', 'name' => 'Kenia', 'prefix' => 'KE', 'number' => '+254'],
            ['id' => '134', 'name' => 'Kirguistán', 'prefix' => 'KG', 'number' => '+996'],
            ['id' => '135', 'name' => 'Kiribati', 'prefix' => 'KI', 'number' => '+686'],
            ['id' => '136', 'name' => 'Kuwait', 'prefix' => 'KW', 'number' => '+965'],
            ['id' => '137', 'name' => 'Laos', 'prefix' => 'LA', 'number' => '+856'],
            ['id' => '138', 'name' => 'Lesoto', 'prefix' => 'LS', 'number' => '+266'],
            ['id' => '139', 'name' => 'Letonia', 'prefix' => 'LV', 'number' => '+371'],
            ['id' => '140', 'name' => 'Líbano', 'prefix' => 'LB', 'number' => '+961'],
            ['id' => '141', 'name' => 'Liberia', 'prefix' => 'LR', 'number' => '+231'],
            ['id' => '142', 'name' => 'Libia', 'prefix' => 'LY', 'number' => '+218'],
            ['id' => '143', 'name' => 'Liechtenstein', 'prefix' => 'LI', 'number' => '+423'],
            ['id' => '144', 'name' => 'Lituania', 'prefix' => 'LT', 'number' => '+370'],
            ['id' => '145', 'name' => 'Luxemburgo', 'prefix' => 'LU', 'number' => '+352'],
            ['id' => '146', 'name' => 'Macao', 'prefix' => 'MO', 'number' => '+853'],
            ['id' => '147', 'name' => 'Macedonia', 'prefix' => 'MK', 'number' => '+389'],
            ['id' => '148', 'name' => 'Madagascar', 'prefix' => 'MG', 'number' => '+261'],
            ['id' => '149', 'name' => 'Malasia', 'prefix' => 'MY', 'number' => '+60'],
            ['id' => '150', 'name' => 'Malawi', 'prefix' => 'MW', 'number' => '+265'],
            ['id' => '151', 'name' => 'Maldivas', 'prefix' => 'MV', 'number' => '+960'],
            ['id' => '152', 'name' => 'Malí', 'prefix' => 'ML', 'number' => '+223'],
            ['id' => '153', 'name' => 'Malta', 'prefix' => 'MT', 'number' => '+356'],
            ['id' => '154', 'name' => 'Maldivas', 'prefix' => 'MV', 'number' => '+960'],
            ['id' => '155', 'name' => 'Marruecos', 'prefix' => 'MA', 'number' => '+212'],
            ['id' => '156', 'name' => 'Martinica', 'prefix' => 'MQ', 'number' => '+596'],
            ['id' => '157', 'name' => 'Mauricio', 'prefix' => 'MU', 'number' => '+230'],
            ['id' => '158', 'name' => 'Mauritania', 'prefix' => 'MR', 'number' => '+222'],
            ['id' => '159', 'name' => 'Mayotte', 'prefix' => 'YT', 'number' => '+262'],
            ['id' => '160', 'name' => 'Micronesia', 'prefix' => 'FM', 'number' => '+691'],
            ['id' => '161', 'name' => 'Moldavia', 'prefix' => 'MD', 'number' => '+373'],
            ['id' => '162', 'name' => 'Mónaco', 'prefix' => 'MC', 'number' => '+377'],
            ['id' => '163', 'name' => 'Mongolia', 'prefix' => 'MN', 'number' => '+976'],
            ['id' => '164', 'name' => 'Montenegro', 'prefix' => 'ME', 'number' => '+382'],
            ['id' => '165', 'name' => 'Montserrat', 'prefix' => 'MS', 'number' => '+1664'],
            ['id' => '166', 'name' => 'Mozambique', 'prefix' => 'MZ', 'number' => '+258'],
            ['id' => '167', 'name' => 'Myanmar', 'prefix' => 'MM', 'number' => '+95'],
            ['id' => '168', 'name' => 'Namibia', 'prefix' => 'NA', 'number' => '+264'],
            ['id' => '169', 'name' => 'Nauru', 'prefix' => 'NR', 'number' => '+674'],
            ['id' => '170', 'name' => 'Nepal', 'prefix' => 'NP', 'number' => '+977'],
            ['id' => '171', 'name' => 'Níger', 'prefix' => 'NE', 'number' => '+227'],
            ['id' => '172', 'name' => 'Nigeria', 'prefix' => 'NG', 'number' => '+234'],
            ['id' => '173', 'name' => 'Niue', 'prefix' => 'NU', 'number' => '+683'],
            ['id' => '174', 'name' => 'Noruega', 'prefix' => 'NO', 'number' => '+47'],
            ['id' => '175', 'name' => 'Nueva Caledonia', 'prefix' => 'NC', 'number' => '+687'],
            ['id' => '176', 'name' => 'Nueva Zelanda', 'prefix' => 'NZ', 'number' => '+64'],
            ['id' => '177', 'name' => 'Omán', 'prefix' => 'OM', 'number' => '+968'],
            ['id' => '178', 'name' => 'Países Bajos', 'prefix' => 'NL', 'number' => '+31'],
            ['id' => '179', 'name' => 'Pakistán', 'prefix' => 'PK', 'number' => '+92'],
            ['id' => '180', 'name' => 'PalaU', 'prefix' => 'PW', 'number' => '+680'],
            ['id' => '181', 'name' => 'Palestina', 'prefix' => 'PS', 'number' => '+970'],
            ['id' => '182', 'name' => 'Papúa Nueva Guinea', 'prefix' => 'PG', 'number' => '+675'],
            ['id' => '183', 'name' => 'Pitcairn', 'prefix' => 'PN', 'number' => '+64'],
            ['id' => '184', 'name' => 'Polinesia Francesa', 'prefix' => 'PF', 'number' => '+689'],
            ['id' => '185', 'name' => 'Polonia', 'prefix' => 'PL', 'number' => '+48'],
            ['id' => '186', 'name' => 'Portugal', 'prefix' => 'PT', 'number' => '+351'],
            ['id' => '187', 'name' => 'Qatar', 'prefix' => 'QA', 'number' => '+974'],
            ['id' => '188', 'name' => 'Reino Unido', 'prefix' => 'GB', 'number' => '+44'],
            ['id' => '189', 'name' => 'República Centroafricana', 'prefix' => 'CF', 'number' => '+236'],
            ['id' => '190', 'name' => 'República Checa', 'prefix' => 'CZ', 'number' => '+420'],
            ['id' => '191', 'name' => 'Reunión', 'prefix' => 'RE', 'number' => '+262'],
            ['id' => '192', 'name' => 'Ruanda', 'prefix' => 'RW', 'number' => '+250'],
            ['id' => '193', 'name' => 'Rumania', 'prefix' => 'RO', 'number' => '+40'],
            ['id' => '194', 'name' => 'Rusia', 'prefix' => 'RU', 'number' => '+7'],
            ['id' => '195', 'name' => 'Sahara Occidental', 'prefix' => 'EH', 'number' => '+212'],
            ['id' => '196', 'name' => 'Samoa', 'prefix' => 'WS', 'number' => '+685'],
            ['id' => '197', 'name' => 'Samoa Americana', 'prefix' => 'AS', 'number' => '+1684'],
            ['id' => '198', 'name' => 'San Bartolomé', 'prefix' => 'BL', 'number' => '+590'],
            ['id' => '199', 'name' => 'San Cristóbal y Nieves', 'prefix' => 'KN', 'number' => '+1869'],
            ['id' => '200', 'name' => 'San Marino', 'prefix' => 'SM', 'number' => '+378'],
            ['id' => '201', 'name' => 'San Martín', 'prefix' => 'MF', 'number' => '+1599'],
            ['id' => '202', 'name' => 'San Pedro y Miquelón', 'prefix' => 'PM', 'number' => '+508'],
            ['id' => '203', 'name' => 'San Vicente y Las Granadinas', 'prefix' => 'VC', 'number' => '+1784'],
            ['id' => '204', 'name' => 'Santa Helena, Ascensión y Tristán de Acuña', 'prefix' => 'SH', 'number' => '+290'],
            ['id' => '205', 'name' => 'Santa Lucía', 'prefix' => 'LC', 'number' => '+1758'],
            ['id' => '206', 'name' => 'Santo Tomé y Príncipe', 'prefix' => 'ST', 'number' => '+239'],
            ['id' => '207', 'name' => 'Senegal', 'prefix' => 'SN', 'number' => '+221'],
            ['id' => '208', 'name' => 'Serbia', 'prefix' => 'RS', 'number' => '+381'],
            ['id' => '209', 'name' => 'Seychelles', 'prefix' => 'SC', 'number' => '+248'],
            ['id' => '210', 'name' => 'Sierra Leona', 'prefix' => 'SL', 'number' => '+232'],
            ['id' => '211', 'name' => 'Singapur', 'prefix' => 'SG', 'number' => '+65'],
            ['id' => '212', 'name' => 'Sint Maarten', 'prefix' => 'SX', 'number' => '+1721'],
            ['id' => '213', 'name' => 'Siria', 'prefix' => 'SY', 'number' => '+963'],
            ['id' => '214', 'name' => 'Somalia', 'prefix' => 'SO', 'number' => '+252'],
            ['id' => '215', 'name' => 'Sri Lanka', 'prefix' => 'LK', 'number' => '+94'],
            ['id' => '216', 'name' => 'Swazilandia', 'prefix' => 'SZ', 'number' => '+268'],
            ['id' => '217', 'name' => 'Sudáfrica', 'prefix' => 'ZA', 'number' => '+27'],
            ['id' => '218', 'name' => 'Sudán', 'prefix' => 'SD', 'number' => '+249'],
            ['id' => '219', 'name' => 'Sudán del Sur', 'prefix' => 'SS', 'number' => '+211'],
            ['id' => '220', 'name' => 'Suecia', 'prefix' => 'SE', 'number' => '+46'],
            ['id' => '221', 'name' => 'Suiza', 'prefix' => 'CH', 'number' => '+41'],
            ['id' => '222', 'name' => 'Surinám', 'prefix' => 'SR', 'number' => '+597'],
            ['id' => '223', 'name' => 'Svalbard y Jan Mayen', 'prefix' => 'SJ', 'number' => '+47'],
            ['id' => '224', 'name' => 'Tailandia', 'prefix' => 'TH', 'number' => '+66'],
            ['id' => '225', 'name' => 'Taiwán', 'prefix' => 'TW', 'number' => '+886'],
            ['id' => '226', 'name' => 'Tanzania', 'prefix' => 'TZ', 'number' => '+255'],
            ['id' => '227', 'name' => 'Tayikistán', 'prefix' => 'TJ', 'number' => '+992'],
            ['id' => '228', 'name' => 'Territorio Británico del Océano Índico', 'prefix' => 'IO', 'number' => '+246'],
            ['id' => '229', 'name' => 'Territorios Australes Franceses', 'prefix' => 'TF', 'number' => '+596'],
            ['id' => '230', 'name' => 'Timor-Leste', 'prefix' => 'TL', 'number' => '+670'],
            ['id' => '231', 'name' => 'Togo', 'prefix' => 'TG', 'number' => '+228'],
            ['id' => '232', 'name' => 'Tokelau', 'prefix' => 'TK', 'number' => '+690'],
            ['id' => '233', 'name' => 'Tonga', 'prefix' => 'TO', 'number' => '+676'],
            ['id' => '234', 'name' => 'Trinidad y Tobago', 'prefix' => 'TT', 'number' => '+1868'],
            ['id' => '235', 'name' => 'Túnez', 'prefix' => 'TN', 'number' => '+216'],
            ['id' => '236', 'name' => 'Turkmenistán', 'prefix' => 'TM', 'number' => '+993'],
            ['id' => '237', 'name' => 'Turquía', 'prefix' => 'TR', 'number' => '+90'],
            ['id' => '238', 'name' => 'Tuvalu', 'prefix' => 'TV', 'number' => '+688'],
            ['id' => '239', 'name' => 'Ucrania', 'prefix' => 'UA', 'number' => '+380'],
            ['id' => '240', 'name' => 'Uganda', 'prefix' => 'UG', 'number' => '+256'],
            ['id' => '241', 'name' => 'Uzbekistán', 'prefix' => 'UZ', 'number' => '+998'],
            ['id' => '242', 'name' => 'Vanuatu', 'prefix' => 'VU', 'number' => '+678'],
            ['id' => '243', 'name' => 'Vaticano', 'prefix' => 'VA', 'number' => '+379'],
            ['id' => '244', 'name' => 'Vietnam', 'prefix' => 'VN', 'number' => '+84'],
            ['id' => '245', 'name' => 'Wallis y Futuna', 'prefix' => 'WF', 'number' => '+681'],
            ['id' => '246', 'name' => 'Yemen', 'prefix' => 'YE', 'number' => '+967'],
            ['id' => '247', 'name' => 'Yibuti', 'prefix' => 'DJ', 'number' => '+253'],
            ['id' => '248', 'name' => 'Zambia', 'prefix' => 'ZM', 'number' => '+260'],
            ['id' => '249', 'name' => 'Zimbabue', 'prefix' => 'ZW', 'number' => '+263'],
            ['id' => '250', 'name' => 'East Timor', 'prefix' => 'TP', 'number' => '+670'],
            ['id' => '251', 'name' => 'Falkland Islands', 'prefix' => 'FK', 'number' => '+500'],
            ['id' => '252', 'name' => 'Guernsey and Alderney', 'prefix' => 'XU', 'number' => '+44'],
            ['id' => '253', 'name' => 'Jersey', 'prefix' => 'XJ', 'number' => '+44'],
            ['id' => '254', 'name' => 'Man (Isle of)', 'prefix' => 'XM', 'number' => '+44'],
            ['id' => '255', 'name' => 'Netherlands Antilles', 'prefix' => 'AN', 'number' => '+599'],
            ['id' => '256', 'name' => 'Smaller Territories of the UK', 'prefix' => 'XG', 'number' => '+44'],
            ['id' => '257', 'name' => 'Yugoslavia', 'prefix' => 'YU', 'number' => '+38']
        ];

        foreach ($countries as $key => $value) {
            $country = new Country();
            $country->id = $value['id'];
            $country->name = $value['name'];
            $country->prefix = $value['prefix'];
            $country->number = $value['number'];
            $country->save();
        }
    }
}
